Name "cmpatrol1"
AbortOnDamage FALSE
AbortOnEnemySighted FALSE
TimeOut 999.0
FaceMoveDir TRUE
YawRate 360
Walkspeed 180
FieldOfView 90

Walk
StartAnim "Walk"
MoveToPos 1000 140 -775
TurnToPos 1500 140 -900
StartAnim "AmbB"
Wait 1.0

Walkspeed 300
StartAnim "Walk"
TurnToPos 0 30 -775
MoveToPos 0 30 -775
TurnToPos 0 30 -500
MoveToPos 0 30 -500
TurnToPos -900 200 -350
MoveToPos -900 200 -350
TurnToPos 0 30 -500
StartAnim "AmbA"
End

